apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rds-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rds-operator.name" . }}
    chart: {{ template "rds-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "rds-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rds-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - rds-operator
          env:
            {{- with .Values.env }}
{{ toYaml . | indent 12 }}
            {{- end }}
            - name: WATCH_NAMESPACE
              value: "{{ .Values.watchNamespace }}"
            - name: OPERATOR_NAME
              value: "{{ .Chart.Name }}"
          {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
