kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "rds-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rds-operator.name" . }}
    chart: {{ template "rds-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: rds-operator
  apiGroup: rbac.authorization.k8s.io
