apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rds-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rds-operator.name" . }}
    chart: {{ template "rds-operator.chart" . }}
    release: {{ .Release.Name }}
    version: "{{ .Chart.Version }}"
